spring:
  application:
    name: eurekaserver
  config:
    import: optional:file:.env[.properties]

server:
  port: ${PORT}
  enable-self-preservation: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false